/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeHighlight: typeof import('./src/views/code-highlight/CodeHighlight.vue')['default']
    CodeHighlite: typeof import('./src/components/CodeHighlite.vue')['default']
    PvButton: typeof import('primevue/button')['default']
    PvButtonGroup: typeof import('primevue/buttongroup')['default']
    PvCard: typeof import('primevue/card')['default']
    PvCheckbox: typeof import('primevue/checkbox')['default']
    PvChip: typeof import('primevue/chip')['default']
    PvDynamicDialog: typeof import('primevue/dynamicdialog')['default']
    PvEditor: typeof import('primevue/editor')['default']
    PvFloatLabel: typeof import('primevue/floatlabel')['default']
    PvForm: typeof import('@primevue/forms/form')['default']
    PvInputText: typeof import('primevue/inputtext')['default']
    PvMenubar: typeof import('primevue/menubar')['default']
    PvMultiSelect: typeof import('primevue/multiselect')['default']
    PvPanel: typeof import('primevue/panel')['default']
    PvProgressBar: typeof import('primevue/progressbar')['default']
    PvProgressSpinner: typeof import('primevue/progressspinner')['default']
    PvSelect: typeof import('primevue/select')['default']
    PvToggleSwitch: typeof import('primevue/toggleswitch')['default']
    PvTree: typeof import('primevue/tree')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
