/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PvButton: typeof import('primevue/button')['default']
    PvButtonGroup: typeof import('primevue/buttongroup')['default']
    PvChip: typeof import('primevue/chip')['default']
    PvDynamicDialog: typeof import('primevue/dynamicdialog')['default']
    PvFloatLabel: typeof import('primevue/floatlabel')['default']
    PvForm: typeof import('@primevue/forms/form')['default']
    PvInputText: typeof import('primevue/inputtext')['default']
    PvMultiSelect: typeof import('primevue/multiselect')['default']
    PvProgressBar: typeof import('primevue/progressbar')['default']
    PvProgressSpinner: typeof import('primevue/progressspinner')['default']
    PvToggleSwitch: typeof import('primevue/toggleswitch')['default']
    PvTree: typeof import('primevue/tree')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
